# Generated by Django 4.0.5 on 2022-06-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_camisas_pantalones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pantalones',
            new_name='Camisa',
        ),
        migrations.RenameModel(
            old_name='Camisas',
            new_name='Pantalon',
        ),
    ]
