# Generated by Django 4.0.5 on 2022-07-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_pantalones_camisa_rename_camisas_pantalon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pantalon',
            options={'verbose_name': 'Pantalon', 'verbose_name_plural': 'Pantalones'},
        ),
        migrations.RemoveField(
            model_name='camisa',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='pantalon',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='remera',
            name='marca',
        ),
        migrations.AddField(
            model_name='camisa',
            name='descripcion',
            field=models.CharField(default='Descripción', max_length=200, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camisa',
            name='modelo',
            field=models.CharField(default='Modelo', max_length=30, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pantalon',
            name='descripcion',
            field=models.CharField(default='Descripción', max_length=200, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pantalon',
            name='modelo',
            field=models.CharField(default='Modelo', max_length=30, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remera',
            name='descripcion',
            field=models.CharField(default='Descropción', max_length=200, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remera',
            name='modelo',
            field=models.CharField(default='Modelo', max_length=30, verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
