# Generated by Django 4.0.5 on 2022-07-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remera_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='camisa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='camisas'),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pantalones'),
        ),
    ]
